# serivce name
spring:
  application:
    name: image-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.1.20.169:5432/intern_demo
    username: postgres
    password: Tdt@6868
# port
server:
  port: 8200
# eureka registry url
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka