spring:
  application:
    name: auth-service
server:
  port: 8100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
app:
  rest-template:
    connect-timeout: 30000 #ms

google:
  sec