# Give a name to the eureka discovery
spring:
  application:
    name: eureka-discovery

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    ndt.project.discovery: INFO


# default port for eureka registry
server:
  port: 8761

  # eureka by default will register itself as a client. So, we need to set it to false.
  # What's a client registry? See other microservices (image, gallery, auth, etc).
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    peer-node-read-timeout-ms: 5000 #ms ~ 5s